<?php

/**
 * Implements hook_theme().
 */
function conference_room_reservation_theme() {
  return [
    'conference_room_book_page' => [
      'variables' => ['form' => NULL],
      'template' => 'conference-room-book-page',
    ],
    'booked_rooms_page' => [
      'variables' => ['booked_rooms' => []], // Define variables expected by the template
      'template' => 'booked-rooms-page', // Name of the Twig template file
    ],
  ];
}
